[build]
  command = "cd SemanticSearch-main && npm ci && npm run build:client"
  functions = "SemanticSearch-main/netlify/functions"
  publish = "SemanticSearch-main/dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
